# Generated by Django 2.1.15 on 2020-03-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200302_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='defaultdays',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='casual_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Leave days per year counter'),
        ),
        migrations.AddField(
            model_name='leave',
            name='paid_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Leave days per year counter'),
        ),
        migrations.AddField(
            model_name='leave',
            name='sick_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Leave days per year counter'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick_Leave'), ('casual', 'Casual_Leave'), ('paid', 'Paid_Leave'), ('study', 'Study_Leave')], default='sick', max_length=25, null=True),
        ),
    ]
