# Generated by Django 2.2.10 on 2020-03-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200309_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinggroup',
            options={'ordering': ['group_name'], 'verbose_name': 'Mail', 'verbose_name_plural': 'Mails'},
        ),
    ]
