# Generated by Django 2.2.10 on 2020-03-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200309_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingGroup',
            new_name='MailingGroups',
        ),
    ]
