# Generated by Django 2.2.10 on 2020-03-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200309_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='groupmail',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
